[2021-07-20 17:09:21,848] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:09:21,858] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:09:21,858] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:21,858] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:09:21,858] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:21,934] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:05:00+00:00
[2021-07-20 17:09:21,940] {standard_task_runner.py:52} INFO - Started process 419594 to run task
[2021-07-20 17:09:21,953] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:05:00+00:00', '--job-id', '298', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpt9ktmwpw', '--error-file', '/tmp/tmpeq1mg6jg']
[2021-07-20 17:09:21,955] {standard_task_runner.py:77} INFO - Job 298: Subtask fuse2
[2021-07-20 17:09:22,659] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:09:22,945] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 17:09:32,450] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:09:32,457] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000500, start_date=20210720T112421, end_date=20210720T112432
[2021-07-20 17:09:32,544] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:09:32,581] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:06:08,467] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:06:08,478] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:06:08,479] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:06:08,479] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:06:08,479] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:06:08,555] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:05:00+00:00
[2021-07-20 18:06:08,559] {standard_task_runner.py:52} INFO - Started process 547179 to run task
[2021-07-20 18:06:08,569] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:05:00+00:00', '--job-id', '298', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpijws4iau', '--error-file', '/tmp/tmp98n60kh9']
[2021-07-20 18:06:08,570] {standard_task_runner.py:77} INFO - Job 298: Subtask fuse2
[2021-07-20 18:06:08,727] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:06:08,948] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 18:06:16,925] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:06:16,931] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000500, start_date=20210720T122108, end_date=20210720T122116
[2021-07-20 18:06:17,873] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:06:17,904] {local_task_job.py:151} INFO - Task exited with return code 0
