[2021-07-20 19:48:52,480] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 19:48:52,490] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 19:48:52,490] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:52,490] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:48:52,490] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:52,918] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:05:00+00:00
[2021-07-20 19:48:52,922] {standard_task_runner.py:52} INFO - Started process 1038618 to run task
[2021-07-20 19:48:52,926] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:05:00+00:00', '--job-id', '325', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcbgp3ftr', '--error-file', '/tmp/tmp0kvjs9ze']
[2021-07-20 19:48:52,927] {standard_task_runner.py:77} INFO - Job 325: Subtask fuse5
[2021-07-20 19:48:53,233] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:48:53,443] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 19:48:56,471] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:48:56,475] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000500, start_date=20210720T140352, end_date=20210720T140356
[2021-07-20 19:48:56,590] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:48:56,633] {local_task_job.py:151} INFO - Task exited with return code 0
