[2021-07-20 16:47:54,180] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 16:47:54,195] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 16:47:54,195] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:47:54,195] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:47:54,195] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:47:54,268] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:04:00+00:00
[2021-07-20 16:47:54,270] {standard_task_runner.py:52} INFO - Started process 407644 to run task
[2021-07-20 16:47:54,276] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:04:00+00:00', '--job-id', '323', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxnd4_xmq', '--error-file', '/tmp/tmpayd8kcyr']
[2021-07-20 16:47:54,277] {standard_task_runner.py:77} INFO - Job 323: Subtask fuse1
[2021-07-20 16:47:54,404] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:47:54,634] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 16:48:01,215] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:48:01,219] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000400, start_date=20210720T110254, end_date=20210720T110301
[2021-07-20 16:48:02,223] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:48:02,252] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:05:29,509] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:05:29,534] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:05:29,534] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:05:29,534] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:05:29,534] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:05:29,624] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:04:00+00:00
[2021-07-20 17:05:29,627] {standard_task_runner.py:52} INFO - Started process 416276 to run task
[2021-07-20 17:05:29,634] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:04:00+00:00', '--job-id', '286', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpf9z5tk8z', '--error-file', '/tmp/tmprq2y2p2s']
[2021-07-20 17:05:29,634] {standard_task_runner.py:77} INFO - Job 286: Subtask fuse1
[2021-07-20 17:05:29,899] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:05:30,136] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 17:05:36,627] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:05:36,632] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000400, start_date=20210720T112029, end_date=20210720T112036
[2021-07-20 17:05:36,711] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:05:36,728] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:02:27,661] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:02:27,695] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:02:27,696] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:27,696] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:02:27,696] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:27,779] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:04:00+00:00
[2021-07-20 18:02:27,785] {standard_task_runner.py:52} INFO - Started process 543909 to run task
[2021-07-20 18:02:27,798] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:04:00+00:00', '--job-id', '286', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp1sqiapve', '--error-file', '/tmp/tmphyraft9u']
[2021-07-20 18:02:27,800] {standard_task_runner.py:77} INFO - Job 286: Subtask fuse1
[2021-07-20 18:02:27,923] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:02:28,524] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 18:02:34,985] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:02:34,989] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000400, start_date=20210720T121727, end_date=20210720T121734
[2021-07-20 18:02:35,119] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:02:35,155] {local_task_job.py:151} INFO - Task exited with return code 0
