[2021-07-20 20:18:08,067] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse9 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 20:18:08,077] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse9 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 20:18:08,077] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 20:18:08,077] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 20:18:08,077] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 20:18:08,173] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse9> on 2021-07-19T00:01:00+00:00
[2021-07-20 20:18:08,178] {standard_task_runner.py:52} INFO - Started process 1200654 to run task
[2021-07-20 20:18:08,191] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse9', '2021-07-19T00:01:00+00:00', '--job-id', '329', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxw21bdio', '--error-file', '/tmp/tmp_xp_vzy6']
[2021-07-20 20:18:08,192] {standard_task_runner.py:77} INFO - Job 329: Subtask fuse9
[2021-07-20 20:18:08,312] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse9 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 20:18:08,500] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse9
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 20:18:24,164] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 20:18:24,201] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse9, execution_date=20210719T000100, start_date=20210720T143308, end_date=20210720T143324
[2021-07-20 20:18:24,375] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 20:18:24,411] {local_task_job.py:151} INFO - Task exited with return code 0
