[2021-07-20 16:48:11,556] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 16:48:11,567] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 16:48:11,567] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:11,567] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:48:11,567] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:11,681] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:05:00+00:00
[2021-07-20 16:48:11,686] {standard_task_runner.py:52} INFO - Started process 407883 to run task
[2021-07-20 16:48:11,699] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:05:00+00:00', '--job-id', '324', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpc26b9bnn', '--error-file', '/tmp/tmpzkt67n9t']
[2021-07-20 16:48:11,701] {standard_task_runner.py:77} INFO - Job 324: Subtask fuse1
[2021-07-20 16:48:11,990] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:48:12,188] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 16:48:19,255] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:48:19,260] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000500, start_date=20210720T110311, end_date=20210720T110319
[2021-07-20 16:48:19,359] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:48:19,389] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:07:04,570] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:07:04,589] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 17:07:04,589] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:04,590] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:07:04,590] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:04,663] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:05:00+00:00
[2021-07-20 17:07:04,669] {standard_task_runner.py:52} INFO - Started process 417696 to run task
[2021-07-20 17:07:04,684] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:05:00+00:00', '--job-id', '291', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphtcrsj9i', '--error-file', '/tmp/tmpmpcvv9y8']
[2021-07-20 17:07:04,685] {standard_task_runner.py:77} INFO - Job 291: Subtask fuse1
[2021-07-20 17:07:04,800] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:07:05,442] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 17:07:11,694] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:07:12,227] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000500, start_date=20210720T112204, end_date=20210720T112212
[2021-07-20 17:07:12,352] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:07:12,361] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:03:55,594] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:03:55,621] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [queued]>
[2021-07-20 18:03:55,621] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:55,621] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:03:55,621] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:55,827] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:05:00+00:00
[2021-07-20 18:03:55,829] {standard_task_runner.py:52} INFO - Started process 545313 to run task
[2021-07-20 18:03:55,834] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:05:00+00:00', '--job-id', '291', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy0nhb6f9', '--error-file', '/tmp/tmpnoyz_q6o']
[2021-07-20 18:03:55,835] {standard_task_runner.py:77} INFO - Job 291: Subtask fuse1
[2021-07-20 18:03:56,082] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:05:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:03:57,121] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:05:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:05:00+00:00
[2021-07-20 18:04:04,587] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:04:04,592] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000500, start_date=20210720T121855, end_date=20210720T121904
[2021-07-20 18:04:06,242] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:04:06,409] {local_task_job.py:151} INFO - Task exited with return code 0
