[2021-07-20 19:48:20,944] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 19:48:21,044] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 19:48:21,045] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:21,045] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:48:21,045] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:48:21,159] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:07:00+00:00
[2021-07-20 19:48:21,165] {standard_task_runner.py:52} INFO - Started process 1038052 to run task
[2021-07-20 19:48:21,177] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:07:00+00:00', '--job-id', '323', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7_hsum50', '--error-file', '/tmp/tmpjwssvr_w']
[2021-07-20 19:48:21,179] {standard_task_runner.py:77} INFO - Job 323: Subtask fuse3
[2021-07-20 19:48:21,364] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:07:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:48:21,582] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:07:00+00:00
[2021-07-20 19:48:24,883] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:48:24,888] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000700, start_date=20210720T140320, end_date=20210720T140324
[2021-07-20 19:48:24,977] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:48:25,002] {local_task_job.py:151} INFO - Task exited with return code 0
