[2021-07-20 16:44:35,301] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 16:44:35,319] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 16:44:35,319] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:44:35,319] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:44:35,319] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:44:36,482] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:00:00+00:00
[2021-07-20 16:44:36,489] {standard_task_runner.py:52} INFO - Started process 405724 to run task
[2021-07-20 16:44:36,504] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:00:00+00:00', '--job-id', '316', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzbz5bou6', '--error-file', '/tmp/tmphg95c449']
[2021-07-20 16:44:36,505] {standard_task_runner.py:77} INFO - Job 316: Subtask fuse1
[2021-07-20 16:44:36,791] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:44:37,106] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 16:44:44,022] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:44:44,053] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000000, start_date=20210720T105935, end_date=20210720T105944
[2021-07-20 16:44:44,384] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:44:44,393] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 16:46:26,729] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 16:46:26,738] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 16:46:26,738] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:46:26,738] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:46:26,738] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:46:26,811] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:00:00+00:00
[2021-07-20 16:46:26,816] {standard_task_runner.py:52} INFO - Started process 406732 to run task
[2021-07-20 16:46:26,828] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:00:00+00:00', '--job-id', '319', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpq7vmr_2n', '--error-file', '/tmp/tmpmu4q6i46']
[2021-07-20 16:46:26,830] {standard_task_runner.py:77} INFO - Job 319: Subtask fuse1
[2021-07-20 16:46:27,102] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:46:28,562] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 16:46:36,691] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:46:36,750] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000000, start_date=20210720T110126, end_date=20210720T110136
[2021-07-20 16:46:36,845] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:46:36,868] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:01:31,118] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:01:31,129] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:01:31,130] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:01:31,130] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:01:31,130] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:01:31,936] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:01:31,944] {standard_task_runner.py:52} INFO - Started process 412420 to run task
[2021-07-20 17:01:31,958] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:00:00+00:00', '--job-id', '276', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpw5fz70j8', '--error-file', '/tmp/tmpzkr1g64e']
[2021-07-20 17:01:31,959] {standard_task_runner.py:77} INFO - Job 276: Subtask fuse1
[2021-07-20 17:01:33,072] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:01:34,963] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:01:43,072] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:01:43,075] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000000, start_date=20210720T111631, end_date=20210720T111643
[2021-07-20 17:01:43,228] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:01:43,268] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:59:03,907] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:59:03,960] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:59:03,960] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:59:03,961] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:59:03,961] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:59:04,048] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:59:04,054] {standard_task_runner.py:52} INFO - Started process 541062 to run task
[2021-07-20 17:59:04,068] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:00:00+00:00', '--job-id', '276', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9_7pal15', '--error-file', '/tmp/tmp8f8r1bpy']
[2021-07-20 17:59:04,070] {standard_task_runner.py:77} INFO - Job 276: Subtask fuse1
[2021-07-20 17:59:04,196] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:59:04,465] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:59:10,529] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:59:10,532] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000000, start_date=20210720T121403, end_date=20210720T121410
[2021-07-20 17:59:10,805] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:59:10,833] {local_task_job.py:151} INFO - Task exited with return code 0
