[2021-07-20 16:50:09,552] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:11:00+00:00 [queued]>
[2021-07-20 16:50:09,563] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:11:00+00:00 [queued]>
[2021-07-20 16:50:09,563] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:50:09,563] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:50:09,563] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:50:09,668] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:11:00+00:00
[2021-07-20 16:50:09,673] {standard_task_runner.py:52} INFO - Started process 409342 to run task
[2021-07-20 16:50:09,683] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:11:00+00:00', '--job-id', '330', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp7bh7py1e', '--error-file', '/tmp/tmp7q274tve']
[2021-07-20 16:50:09,685] {standard_task_runner.py:77} INFO - Job 330: Subtask fuse1
[2021-07-20 16:50:09,899] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:11:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:50:10,196] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:11:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:11:00+00:00
[2021-07-20 16:50:15,808] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:50:15,816] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T001100, start_date=20210720T110509, end_date=20210720T110515
[2021-07-20 16:50:15,916] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:50:15,960] {local_task_job.py:151} INFO - Task exited with return code 0
