[2021-07-20 17:07:20,839] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:07:20,849] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:07:20,849] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:20,849] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:07:20,849] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:07:21,606] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:04:00+00:00
[2021-07-20 17:07:21,611] {standard_task_runner.py:52} INFO - Started process 417903 to run task
[2021-07-20 17:07:21,625] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:04:00+00:00', '--job-id', '292', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyred2jzf', '--error-file', '/tmp/tmp0iqm8d5z']
[2021-07-20 17:07:21,627] {standard_task_runner.py:77} INFO - Job 292: Subtask fuse2
[2021-07-20 17:07:21,794] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:07:22,033] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 17:07:32,995] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:07:33,104] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000400, start_date=20210720T112220, end_date=20210720T112233
[2021-07-20 17:07:33,682] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:07:33,704] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:04:14,686] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:04:14,698] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:04:14,698] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:04:14,698] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:04:14,698] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:04:15,031] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:04:00+00:00
[2021-07-20 18:04:15,037] {standard_task_runner.py:52} INFO - Started process 545542 to run task
[2021-07-20 18:04:15,048] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:04:00+00:00', '--job-id', '292', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpy286x7ax', '--error-file', '/tmp/tmp0pp8f876']
[2021-07-20 18:04:15,050] {standard_task_runner.py:77} INFO - Job 292: Subtask fuse2
[2021-07-20 18:04:15,216] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:04:16,702] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 18:04:26,936] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:04:26,942] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000400, start_date=20210720T121914, end_date=20210720T121926
[2021-07-20 18:04:27,127] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:04:27,151] {local_task_job.py:151} INFO - Task exited with return code 0
