[2021-07-20 16:48:55,554] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 16:48:55,567] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 16:48:55,567] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:55,567] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:48:55,567] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:55,653] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:07:00+00:00
[2021-07-20 16:48:55,655] {standard_task_runner.py:52} INFO - Started process 408438 to run task
[2021-07-20 16:48:55,661] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:07:00+00:00', '--job-id', '326', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_65sxvl9', '--error-file', '/tmp/tmpd3059pyq']
[2021-07-20 16:48:55,662] {standard_task_runner.py:77} INFO - Job 326: Subtask fuse1
[2021-07-20 16:48:55,793] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:48:56,668] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:07:00+00:00
[2021-07-20 16:49:01,518] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:49:01,521] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000700, start_date=20210720T110355, end_date=20210720T110401
[2021-07-20 16:49:01,646] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:49:01,667] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:38:03,534] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 17:38:03,558] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 17:38:03,558] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:38:03,558] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:38:03,558] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:38:03,659] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:07:00+00:00
[2021-07-20 17:38:03,666] {standard_task_runner.py:52} INFO - Started process 533685 to run task
[2021-07-20 17:38:03,677] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:07:00+00:00', '--job-id', '304', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpj8ue9em0', '--error-file', '/tmp/tmpfiebeb9s']
[2021-07-20 17:38:03,678] {standard_task_runner.py:77} INFO - Job 304: Subtask fuse1
[2021-07-20 17:38:03,837] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:38:04,125] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:07:00+00:00
[2021-07-20 17:38:12,820] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:38:12,824] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000700, start_date=20210720T115303, end_date=20210720T115312
[2021-07-20 17:38:12,935] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:38:12,974] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:38:54,257] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 18:38:54,283] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [queued]>
[2021-07-20 18:38:54,283] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:38:54,283] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:38:54,283] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:38:54,365] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:07:00+00:00
[2021-07-20 18:38:54,371] {standard_task_runner.py:52} INFO - Started process 710504 to run task
[2021-07-20 18:38:54,379] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:07:00+00:00', '--job-id', '304', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9g__vxzy', '--error-file', '/tmp/tmpbbop4d1s']
[2021-07-20 18:38:54,380] {standard_task_runner.py:77} INFO - Job 304: Subtask fuse1
[2021-07-20 18:38:54,838] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:07:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:38:56,670] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:07:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:07:00+00:00
[2021-07-20 18:39:06,076] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:39:06,080] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000700, start_date=20210720T125354, end_date=20210720T125406
[2021-07-20 18:39:06,207] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:39:06,219] {local_task_job.py:151} INFO - Task exited with return code 0
