[2021-07-20 19:46:50,142] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse8 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 19:46:50,161] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse8 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 19:46:50,161] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:46:50,161] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:46:50,161] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:46:51,291] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse8> on 2021-07-19T00:01:00+00:00
[2021-07-20 19:46:51,295] {standard_task_runner.py:52} INFO - Started process 1036800 to run task
[2021-07-20 19:46:51,299] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse8', '2021-07-19T00:01:00+00:00', '--job-id', '319', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpq19m51ph', '--error-file', '/tmp/tmpkkwy1vm5']
[2021-07-20 19:46:51,299] {standard_task_runner.py:77} INFO - Job 319: Subtask fuse8
[2021-07-20 19:46:52,033] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse8 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:46:53,104] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse8
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 19:47:02,274] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:47:02,340] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse8, execution_date=20210719T000100, start_date=20210720T140150, end_date=20210720T140202
[2021-07-20 19:47:02,460] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:47:02,475] {local_task_job.py:151} INFO - Task exited with return code 0
