[2021-07-20 17:03:05,552] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:03:05,561] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:03:05,562] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:03:05,562] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:03:05,562] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:03:05,742] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:03:05,744] {standard_task_runner.py:52} INFO - Started process 414342 to run task
[2021-07-20 17:03:05,748] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:01:00+00:00', '--job-id', '280', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpmlsxw_sk', '--error-file', '/tmp/tmpda3hp8qo']
[2021-07-20 17:03:05,749] {standard_task_runner.py:77} INFO - Job 280: Subtask fuse2
[2021-07-20 17:03:07,516] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:03:08,172] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:03:18,593] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:03:18,599] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000100, start_date=20210720T111805, end_date=20210720T111818
[2021-07-20 17:03:18,837] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:03:18,855] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:00:24,389] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:00:24,412] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:00:24,412] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:00:24,412] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:00:24,412] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:00:24,642] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:01:00+00:00
[2021-07-20 18:00:24,648] {standard_task_runner.py:52} INFO - Started process 542018 to run task
[2021-07-20 18:00:24,661] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:01:00+00:00', '--job-id', '280', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4c2p4uo6', '--error-file', '/tmp/tmp_v3ldjzm']
[2021-07-20 18:00:24,663] {standard_task_runner.py:77} INFO - Job 280: Subtask fuse2
[2021-07-20 18:00:25,694] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:00:25,931] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 18:00:35,497] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:00:35,502] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000100, start_date=20210720T121524, end_date=20210720T121535
[2021-07-20 18:00:35,717] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:00:35,732] {local_task_job.py:151} INFO - Task exited with return code 0
