[2021-07-20 17:06:42,027] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:06:42,034] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 17:06:42,035] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:42,035] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:06:42,035] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:42,110] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:00:00+00:00
[2021-07-20 17:06:42,112] {standard_task_runner.py:52} INFO - Started process 417349 to run task
[2021-07-20 17:06:42,115] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:00:00+00:00', '--job-id', '290', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppwo1mix9', '--error-file', '/tmp/tmpebvj_kmr']
[2021-07-20 17:06:42,116] {standard_task_runner.py:77} INFO - Job 290: Subtask fuse5
[2021-07-20 17:06:42,226] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:06:42,539] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 17:06:46,349] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:06:46,353] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000000, start_date=20210720T112142, end_date=20210720T112146
[2021-07-20 17:06:46,595] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:06:46,621] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:03:36,381] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:03:36,388] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [queued]>
[2021-07-20 18:03:36,388] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:36,388] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:03:36,388] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:36,457] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:00:00+00:00
[2021-07-20 18:03:36,460] {standard_task_runner.py:52} INFO - Started process 544987 to run task
[2021-07-20 18:03:36,467] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:00:00+00:00', '--job-id', '290', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpwp68ctq2', '--error-file', '/tmp/tmp4ftbup8u']
[2021-07-20 18:03:36,467] {standard_task_runner.py:77} INFO - Job 290: Subtask fuse5
[2021-07-20 18:03:36,633] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:03:37,010] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:00:00+00:00
[2021-07-20 18:03:40,214] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:03:40,217] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000000, start_date=20210720T121836, end_date=20210720T121840
[2021-07-20 18:03:40,407] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:03:40,413] {local_task_job.py:151} INFO - Task exited with return code 0
