[2021-07-20 19:16:37,322] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 19:16:37,333] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse5 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 19:16:37,333] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:16:37,333] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:16:37,333] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:16:37,443] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse5> on 2021-07-19T00:04:00+00:00
[2021-07-20 19:16:37,448] {standard_task_runner.py:52} INFO - Started process 875093 to run task
[2021-07-20 19:16:37,458] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse5', '2021-07-19T00:04:00+00:00', '--job-id', '316', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnb0rc6mk', '--error-file', '/tmp/tmpg4v5k68u']
[2021-07-20 19:16:37,459] {standard_task_runner.py:77} INFO - Job 316: Subtask fuse5
[2021-07-20 19:16:37,581] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse5 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:16:37,892] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse5
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 19:16:41,539] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:16:41,542] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse5, execution_date=20210719T000400, start_date=20210720T133137, end_date=20210720T133141
[2021-07-20 19:16:41,874] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:16:41,881] {local_task_job.py:151} INFO - Task exited with return code 0
