[2021-07-20 18:40:58,523] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:40:58,535] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 18:40:58,535] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:40:58,535] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:40:58,535] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:40:58,618] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse7> on 2021-07-19T00:01:00+00:00
[2021-07-20 18:40:58,623] {standard_task_runner.py:52} INFO - Started process 712021 to run task
[2021-07-20 18:40:58,635] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse7', '2021-07-19T00:01:00+00:00', '--job-id', '310', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpr7_s3ndo', '--error-file', '/tmp/tmpxldd62u8']
[2021-07-20 18:40:58,636] {standard_task_runner.py:77} INFO - Job 310: Subtask fuse7
[2021-07-20 18:40:58,794] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse7 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:40:59,013] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse7
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 19:14:53,429] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:14:55,272] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse7, execution_date=20210719T000100, start_date=20210720T125558, end_date=20210720T132955
[2021-07-20 19:14:55,466] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:14:55,502] {local_task_job.py:151} INFO - Task exited with return code 0
