[2021-07-20 16:44:59,079] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 16:44:59,098] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 16:44:59,098] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:44:59,099] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:44:59,099] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:44:59,176] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:01:00+00:00
[2021-07-20 16:44:59,179] {standard_task_runner.py:52} INFO - Started process 405962 to run task
[2021-07-20 16:44:59,183] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:01:00+00:00', '--job-id', '317', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppgy7_oee', '--error-file', '/tmp/tmpz72ubp3i']
[2021-07-20 16:44:59,183] {standard_task_runner.py:77} INFO - Job 317: Subtask fuse1
[2021-07-20 16:44:59,318] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:44:59,596] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 16:45:06,133] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:45:06,138] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000100, start_date=20210720T105959, end_date=20210720T110006
[2021-07-20 16:45:06,291] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:45:06,334] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 16:46:49,825] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 16:46:49,837] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 16:46:49,838] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:46:49,839] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:46:49,839] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:46:50,470] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:01:00+00:00
[2021-07-20 16:46:50,476] {standard_task_runner.py:52} INFO - Started process 406954 to run task
[2021-07-20 16:46:50,486] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:01:00+00:00', '--job-id', '320', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpylj4tpk1', '--error-file', '/tmp/tmppi0z7u1m']
[2021-07-20 16:46:50,487] {standard_task_runner.py:77} INFO - Job 320: Subtask fuse1
[2021-07-20 16:46:50,596] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:46:50,765] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 16:46:58,543] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:46:58,547] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000100, start_date=20210720T110149, end_date=20210720T110158
[2021-07-20 16:46:58,673] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:46:58,707] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:01:55,228] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:01:55,237] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:01:55,237] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:01:55,237] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:01:55,237] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:01:55,308] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:01:55,313] {standard_task_runner.py:52} INFO - Started process 412630 to run task
[2021-07-20 17:01:55,325] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:01:00+00:00', '--job-id', '277', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp0nvrfmia', '--error-file', '/tmp/tmphneks3z9']
[2021-07-20 17:01:55,327] {standard_task_runner.py:77} INFO - Job 277: Subtask fuse1
[2021-07-20 17:01:55,478] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:01:55,702] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:02:02,397] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:02:02,400] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000100, start_date=20210720T111655, end_date=20210720T111702
[2021-07-20 17:02:02,506] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:02:02,520] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:59:22,831] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:59:22,842] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [queued]>
[2021-07-20 17:59:22,843] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:59:22,843] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:59:22,843] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:59:22,919] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:01:00+00:00
[2021-07-20 17:59:22,925] {standard_task_runner.py:52} INFO - Started process 541285 to run task
[2021-07-20 17:59:22,939] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:01:00+00:00', '--job-id', '277', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9sy11rga', '--error-file', '/tmp/tmpy76x6t5t']
[2021-07-20 17:59:22,940] {standard_task_runner.py:77} INFO - Job 277: Subtask fuse1
[2021-07-20 17:59:23,040] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:01:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:59:23,258] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:01:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:01:00+00:00
[2021-07-20 17:59:29,473] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:59:29,479] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000100, start_date=20210720T121422, end_date=20210720T121429
[2021-07-20 17:59:29,598] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:59:29,641] {local_task_job.py:151} INFO - Task exited with return code 0
