[2021-07-20 19:17:00,933] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 19:17:00,943] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse7 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 19:17:00,944] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:17:00,944] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 19:17:00,944] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 19:17:01,019] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse7> on 2021-07-19T00:02:00+00:00
[2021-07-20 19:17:01,023] {standard_task_runner.py:52} INFO - Started process 875499 to run task
[2021-07-20 19:17:01,033] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse7', '2021-07-19T00:02:00+00:00', '--job-id', '318', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2fipz2r_', '--error-file', '/tmp/tmpieo0lz9r']
[2021-07-20 19:17:01,035] {standard_task_runner.py:77} INFO - Job 318: Subtask fuse7
[2021-07-20 19:17:01,192] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse7 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 19:17:01,446] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse7
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 19:46:41,424] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 19:46:41,429] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse7, execution_date=20210719T000200, start_date=20210720T133200, end_date=20210720T140141
[2021-07-20 19:46:41,622] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 19:46:41,664] {local_task_job.py:151} INFO - Task exited with return code 0
