[2021-07-20 17:06:09,005] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:06:09,016] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 17:06:09,016] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:09,016] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:06:09,016] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:06:09,878] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:02:00+00:00
[2021-07-20 17:06:09,882] {standard_task_runner.py:52} INFO - Started process 416786 to run task
[2021-07-20 17:06:09,890] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:02:00+00:00', '--job-id', '288', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpo_s0w_n0', '--error-file', '/tmp/tmpypuoitvx']
[2021-07-20 17:06:09,891] {standard_task_runner.py:77} INFO - Job 288: Subtask fuse3
[2021-07-20 17:06:10,496] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:06:10,725] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 17:06:14,672] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:06:15,007] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000200, start_date=20210720T112109, end_date=20210720T112115
[2021-07-20 17:06:15,146] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:06:15,154] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:03:01,539] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:03:01,551] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [queued]>
[2021-07-20 18:03:01,551] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:01,551] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:03:01,551] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:03:01,624] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:02:00+00:00
[2021-07-20 18:03:01,630] {standard_task_runner.py:52} INFO - Started process 544407 to run task
[2021-07-20 18:03:01,640] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:02:00+00:00', '--job-id', '288', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzsi35vg0', '--error-file', '/tmp/tmpbx2_4l_q']
[2021-07-20 18:03:01,641] {standard_task_runner.py:77} INFO - Job 288: Subtask fuse3
[2021-07-20 18:03:01,797] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:02:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:03:03,369] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:02:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:02:00+00:00
[2021-07-20 18:03:08,986] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:03:08,989] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000200, start_date=20210720T121801, end_date=20210720T121808
[2021-07-20 18:03:09,100] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:03:09,114] {local_task_job.py:151} INFO - Task exited with return code 0
