[2021-07-20 16:48:32,218] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 16:48:32,230] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 16:48:32,230] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:32,230] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:48:32,230] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:48:32,305] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:06:00+00:00
[2021-07-20 16:48:32,308] {standard_task_runner.py:52} INFO - Started process 408104 to run task
[2021-07-20 16:48:32,312] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:06:00+00:00', '--job-id', '325', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyzsb8e4s', '--error-file', '/tmp/tmp69b2riny']
[2021-07-20 16:48:32,313] {standard_task_runner.py:77} INFO - Job 325: Subtask fuse1
[2021-07-20 16:48:32,547] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:48:33,029] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:06:00+00:00
[2021-07-20 16:48:41,013] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:48:41,017] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000600, start_date=20210720T110332, end_date=20210720T110341
[2021-07-20 16:48:41,786] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:48:41,806] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 17:09:03,116] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 17:09:03,139] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 17:09:03,139] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:03,139] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:09:03,139] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:03,220] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:06:00+00:00
[2021-07-20 17:09:03,222] {standard_task_runner.py:52} INFO - Started process 419360 to run task
[2021-07-20 17:09:03,228] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:06:00+00:00', '--job-id', '297', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpkb5tk80s', '--error-file', '/tmp/tmpol47g277']
[2021-07-20 17:09:03,229] {standard_task_runner.py:77} INFO - Job 297: Subtask fuse1
[2021-07-20 17:09:03,319] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:09:03,530] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:06:00+00:00
[2021-07-20 17:09:10,298] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:09:10,303] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000600, start_date=20210720T112403, end_date=20210720T112410
[2021-07-20 17:09:10,395] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:09:10,416] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:05:54,763] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 18:05:54,774] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [queued]>
[2021-07-20 18:05:54,774] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:05:54,774] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:05:54,774] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:05:54,845] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:06:00+00:00
[2021-07-20 18:05:54,849] {standard_task_runner.py:52} INFO - Started process 546953 to run task
[2021-07-20 18:05:54,859] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:06:00+00:00', '--job-id', '297', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsrrxbygg', '--error-file', '/tmp/tmp838qrkmf']
[2021-07-20 18:05:54,861] {standard_task_runner.py:77} INFO - Job 297: Subtask fuse1
[2021-07-20 18:05:55,018] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:06:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:05:55,350] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:06:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:06:00+00:00
[2021-07-20 18:06:01,763] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:06:01,767] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T000600, start_date=20210720T122054, end_date=20210720T122101
[2021-07-20 18:06:01,850] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:06:01,869] {local_task_job.py:151} INFO - Task exited with return code 0
