[2021-07-20 17:09:42,855] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:09:42,869] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 17:09:42,869] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:42,869] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:09:42,869] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:09:43,408] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:04:00+00:00
[2021-07-20 17:09:43,415] {standard_task_runner.py:52} INFO - Started process 419866 to run task
[2021-07-20 17:09:43,423] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:04:00+00:00', '--job-id', '299', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpo_02dya2', '--error-file', '/tmp/tmpg7ipn4w5']
[2021-07-20 17:09:43,424] {standard_task_runner.py:77} INFO - Job 299: Subtask fuse3
[2021-07-20 17:09:43,670] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:09:43,975] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 17:09:47,203] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:09:47,207] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000400, start_date=20210720T112442, end_date=20210720T112447
[2021-07-20 17:09:47,528] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:09:47,565] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:06:24,768] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:06:24,794] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [queued]>
[2021-07-20 18:06:24,794] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:06:24,794] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:06:24,794] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:06:24,892] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse3> on 2021-07-19T00:04:00+00:00
[2021-07-20 18:06:24,896] {standard_task_runner.py:52} INFO - Started process 547455 to run task
[2021-07-20 18:06:24,906] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse3', '2021-07-19T00:04:00+00:00', '--job-id', '299', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp597p53q_', '--error-file', '/tmp/tmpadl_l7_p']
[2021-07-20 18:06:24,908] {standard_task_runner.py:77} INFO - Job 299: Subtask fuse3
[2021-07-20 18:06:25,065] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse3 2021-07-19T00:04:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:06:25,285] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse3
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:04:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:04:00+00:00
[2021-07-20 18:06:28,264] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:06:28,268] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse3, execution_date=20210719T000400, start_date=20210720T122124, end_date=20210720T122128
[2021-07-20 18:06:28,354] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:06:28,365] {local_task_job.py:151} INFO - Task exited with return code 0
