[2021-07-20 17:05:46,751] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [queued]>
[2021-07-20 17:05:46,764] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [queued]>
[2021-07-20 17:05:46,764] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:05:46,764] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 17:05:46,764] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 17:05:46,858] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:03:00+00:00
[2021-07-20 17:05:46,864] {standard_task_runner.py:52} INFO - Started process 416482 to run task
[2021-07-20 17:05:46,877] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:03:00+00:00', '--job-id', '287', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpyn_g4tyq', '--error-file', '/tmp/tmp6kl8jgye']
[2021-07-20 17:05:46,879] {standard_task_runner.py:77} INFO - Job 287: Subtask fuse2
[2021-07-20 17:05:47,015] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 17:05:47,215] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:03:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:03:00+00:00
[2021-07-20 17:05:59,387] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 17:05:59,393] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000300, start_date=20210720T112046, end_date=20210720T112059
[2021-07-20 17:05:59,562] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 17:05:59,583] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-07-20 18:02:43,427] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [queued]>
[2021-07-20 18:02:43,452] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [queued]>
[2021-07-20 18:02:43,452] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:43,452] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 18:02:43,452] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 18:02:43,695] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse2> on 2021-07-19T00:03:00+00:00
[2021-07-20 18:02:43,701] {standard_task_runner.py:52} INFO - Started process 544118 to run task
[2021-07-20 18:02:43,713] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse2', '2021-07-19T00:03:00+00:00', '--job-id', '287', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9ob048io', '--error-file', '/tmp/tmpuzw34u70']
[2021-07-20 18:02:43,715] {standard_task_runner.py:77} INFO - Job 287: Subtask fuse2
[2021-07-20 18:02:43,834] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse2 2021-07-19T00:03:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 18:02:44,055] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse2
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:03:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:03:00+00:00
[2021-07-20 18:02:53,601] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 18:02:53,607] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse2, execution_date=20210719T000300, start_date=20210720T121743, end_date=20210720T121753
[2021-07-20 18:02:53,722] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 18:02:53,751] {local_task_job.py:151} INFO - Task exited with return code 0
