[2021-07-20 16:51:57,591] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:16:00+00:00 [queued]>
[2021-07-20 16:51:57,601] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fuse.fuse1 2021-07-19T00:16:00+00:00 [queued]>
[2021-07-20 16:51:57,601] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:51:57,601] {taskinstance.py:1068} INFO - Starting attempt 1 of 8
[2021-07-20 16:51:57,601] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-20 16:51:58,498] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): fuse1> on 2021-07-19T00:16:00+00:00
[2021-07-20 16:51:58,505] {standard_task_runner.py:52} INFO - Started process 410611 to run task
[2021-07-20 16:51:58,515] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fuse', 'fuse1', '2021-07-19T00:16:00+00:00', '--job-id', '335', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpejkwm4ak', '--error-file', '/tmp/tmpgzt9l2da']
[2021-07-20 16:51:58,516] {standard_task_runner.py:77} INFO - Job 335: Subtask fuse1
[2021-07-20 16:51:58,879] {logging_mixin.py:104} INFO - Running <TaskInstance: Fuse.fuse1 2021-07-19T00:16:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-20 16:51:59,322] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fuse
AIRFLOW_CTX_TASK_ID=fuse1
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T00:16:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-19T00:16:00+00:00
[2021-07-20 16:52:07,611] {python.py:151} INFO - Done. Returned value was: None
[2021-07-20 16:52:07,614] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=Fuse, task_id=fuse1, execution_date=20210719T001600, start_date=20210720T110657, end_date=20210720T110707
[2021-07-20 16:52:07,841] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-07-20 16:52:07,881] {local_task_job.py:151} INFO - Task exited with return code 0
